services:
  redis:
    image: redis:7-alpine
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    env_file:
      - .env.docker
    restart: always

  transcripter:
    build:
      context: .
      dockerfile: apps/mq/Dockerfile
    working_dir: /app/apps/mq
    command: ["bun", "run", "start:transcripter"]
    depends_on:
      - redis
    env_file:
      - .env.docker
    restart: always

  summarizer:
    build:
      context: .
      dockerfile: apps/mq/Dockerfile
    working_dir: /app/apps/mq
    command: ["bun", "run", "start:summarizer"]
    depends_on:
      - redis
    env_file:
      - .env.docker
    restart: always
